import type { Recipe } from "@/types/recipe"

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    slug: "creamy-garlic-tuscan-salmon",
    title: "Creamy Garlic Tuscan Salmon",
    description:
      "Pan-seared salmon in a creamy garlic sauce with sun-dried tomatoes and spinach. A restaurant-quality dish ready in 30 minutes.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    categories: ["dinner", "healthy", "seafood"],
    difficulty: "medium",
    prepTime: 10,
    cookTime: 20,
    totalTime: 30,
    servings: 4,
    nutrition: {
      calories: 485,
      protein: 38,
      carbs: 8,
      fat: 32,
    },
    ingredients: [
      { id: "1", name: "Salmon fillets", amount: 4, unit: "pieces" },
      { id: "2", name: "Heavy cream", amount: 1, unit: "cup" },
      { id: "3", name: "Garlic", amount: 4, unit: "cloves" },
      { id: "4", name: "Sun-dried tomatoes", amount: 0.5, unit: "cup" },
      { id: "5", name: "Spinach", amount: 2, unit: "cups" },
    ],
    instructions: [
      "Season salmon with salt and pepper.",
      "Heat oil in a large skillet over medium-high heat.",
      "Sear salmon for 4 minutes per side, then remove from pan.",
      "Add garlic and cook for 1 minute.",
      "Pour in cream and add sun-dried tomatoes.",
      "Simmer for 3 minutes, then add spinach.",
      "Return salmon to the pan and serve.",
    ],
    author: { id: "1", name: "Chef Maria", avatarUrl: "/placeholder.svg?height=40&width=40" },
    likes: 234,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    slug: "fluffy-japanese-pancakes",
    title: "Fluffy Japanese Pancakes",
    description:
      "Incredibly thick and fluffy soufflé pancakes that are light as air. Perfect for a special weekend breakfast.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    categories: ["breakfast", "dessert"],
    difficulty: "hard",
    prepTime: 20,
    cookTime: 25,
    totalTime: 45,
    servings: 2,
    nutrition: {
      calories: 320,
      protein: 12,
      carbs: 42,
      fat: 14,
    },
    ingredients: [
      { id: "1", name: "Eggs", amount: 2, unit: "large" },
      { id: "2", name: "Milk", amount: 3, unit: "tbsp" },
      { id: "3", name: "Flour", amount: 0.25, unit: "cup" },
      { id: "4", name: "Sugar", amount: 2, unit: "tbsp" },
      { id: "5", name: "Baking powder", amount: 0.5, unit: "tsp" },
    ],
    instructions: [
      "Separate egg whites and yolks.",
      "Mix yolks with milk, flour, and baking powder.",
      "Beat egg whites until stiff peaks form.",
      "Gently fold egg whites into batter.",
      "Cook on low heat in ring molds for 10-12 minutes per side.",
      "Serve with butter and maple syrup.",
    ],
    author: { id: "2", name: "Yuki Tanaka", avatarUrl: "/placeholder.svg?height=40&width=40" },
    likes: 567,
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-01-10T08:00:00Z",
  },
  {
    id: "3",
    slug: "mediterranean-quinoa-bowl",
    title: "Mediterranean Quinoa Bowl",
    description:
      "A nutritious and colorful bowl packed with quinoa, fresh vegetables, feta cheese, and a lemon herb dressing.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    categories: ["healthy", "lunch", "vegetarian"],
    difficulty: "easy",
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    servings: 4,
    nutrition: {
      calories: 385,
      protein: 14,
      carbs: 48,
      fat: 16,
    },
    ingredients: [
      { id: "1", name: "Quinoa", amount: 1, unit: "cup" },
      { id: "2", name: "Cherry tomatoes", amount: 1, unit: "cup" },
      { id: "3", name: "Cucumber", amount: 1, unit: "medium" },
      { id: "4", name: "Feta cheese", amount: 0.5, unit: "cup" },
      { id: "5", name: "Kalamata olives", amount: 0.25, unit: "cup" },
    ],
    instructions: [
      "Cook quinoa according to package directions and let cool.",
      "Chop vegetables into bite-sized pieces.",
      "Whisk together olive oil, lemon juice, and herbs for dressing.",
      "Combine quinoa with vegetables in a large bowl.",
      "Top with feta and olives.",
      "Drizzle with dressing and serve.",
    ],
    author: { id: "3", name: "Alex Green", avatarUrl: "/placeholder.svg?height=40&width=40" },
    likes: 412,
    createdAt: "2024-01-12T12:00:00Z",
    updatedAt: "2024-01-12T12:00:00Z",
  },
  {
    id: "4",
    slug: "classic-beef-burger",
    title: "Classic Beef Burger",
    description: "Juicy homemade beef patties with all the fixings. Learn the secrets to the perfect backyard burger.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    categories: ["dinner", "american"],
    difficulty: "easy",
    prepTime: 15,
    cookTime: 10,
    totalTime: 25,
    servings: 4,
    nutrition: {
      calories: 550,
      protein: 32,
      carbs: 35,
      fat: 30,
    },
    ingredients: [
      { id: "1", name: "Ground beef", amount: 1, unit: "lb" },
      { id: "2", name: "Burger buns", amount: 4, unit: "pieces" },
      { id: "3", name: "Cheddar cheese", amount: 4, unit: "slices" },
      { id: "4", name: "Lettuce", amount: 4, unit: "leaves" },
      { id: "5", name: "Tomato", amount: 1, unit: "large" },
    ],
    instructions: [
      "Divide beef into 4 portions and form patties.",
      "Season with salt and pepper.",
      "Grill or pan-fry for 4-5 minutes per side.",
      "Add cheese in the last minute of cooking.",
      "Toast buns and assemble with your favorite toppings.",
    ],
    author: { id: "1", name: "Chef Maria", avatarUrl: "/placeholder.svg?height=40&width=40" },
    likes: 289,
    createdAt: "2024-01-08T18:00:00Z",
    updatedAt: "2024-01-08T18:00:00Z",
  },
  {
    id: "5",
    slug: "chocolate-lava-cake",
    title: "Chocolate Lava Cake",
    description:
      "Decadent individual chocolate cakes with a molten center. An impressive dessert that's easier than you think.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    categories: ["dessert"],
    difficulty: "medium",
    prepTime: 15,
    cookTime: 12,
    totalTime: 27,
    servings: 4,
    nutrition: {
      calories: 420,
      protein: 6,
      carbs: 38,
      fat: 28,
    },
    ingredients: [
      { id: "1", name: "Dark chocolate", amount: 4, unit: "oz" },
      { id: "2", name: "Butter", amount: 4, unit: "tbsp" },
      { id: "3", name: "Eggs", amount: 2, unit: "large" },
      { id: "4", name: "Sugar", amount: 0.25, unit: "cup" },
      { id: "5", name: "Flour", amount: 2, unit: "tbsp" },
    ],
    instructions: [
      "Preheat oven to 425°F (220°C).",
      "Melt chocolate and butter together.",
      "Whisk eggs and sugar until thick.",
      "Fold chocolate mixture into eggs, then add flour.",
      "Pour into greased ramekins.",
      "Bake for 12 minutes until edges are firm but center is soft.",
      "Invert onto plates and serve immediately.",
    ],
    author: { id: "4", name: "Pastry Pro", avatarUrl: "/placeholder.svg?height=40&width=40" },
    likes: 678,
    createdAt: "2024-01-05T20:00:00Z",
    updatedAt: "2024-01-05T20:00:00Z",
  },
  {
    id: "6",
    slug: "avocado-toast-supreme",
    title: "Avocado Toast Supreme",
    description: "Elevated avocado toast with poached eggs, everything bagel seasoning, and microgreens on sourdough.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    categories: ["breakfast", "healthy"],
    difficulty: "easy",
    prepTime: 10,
    cookTime: 5,
    totalTime: 15,
    servings: 2,
    nutrition: {
      calories: 310,
      protein: 14,
      carbs: 28,
      fat: 18,
    },
    ingredients: [
      { id: "1", name: "Sourdough bread", amount: 2, unit: "slices" },
      { id: "2", name: "Avocado", amount: 1, unit: "ripe" },
      { id: "3", name: "Eggs", amount: 2, unit: "large" },
      { id: "4", name: "Everything bagel seasoning", amount: 1, unit: "tsp" },
      { id: "5", name: "Microgreens", amount: 0.25, unit: "cup" },
    ],
    instructions: [
      "Toast sourdough slices until golden.",
      "Mash avocado with salt, pepper, and lemon juice.",
      "Poach eggs in simmering water with vinegar.",
      "Spread avocado on toast.",
      "Top with poached eggs and seasoning.",
      "Garnish with microgreens.",
    ],
    author: { id: "3", name: "Alex Green", avatarUrl: "/placeholder.svg?height=40&width=40" },
    likes: 445,
    createdAt: "2024-01-14T09:00:00Z",
    updatedAt: "2024-01-14T09:00:00Z",
  },
]
