import type { Recipe } from "./types"

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    slug: "creamy-tuscan-chicken",
    title: "Creamy Tuscan Chicken",
    description: "A rich and flavorful Italian-inspired dish with sun-dried tomatoes and spinach.",
    image: "/placeholder.svg?height=400&width=600",
    categories: ["dinner", "italian", "chicken"],
    difficulty: "medium",
    time: 35,
    servings: 4,
    calories: 450,
    protein: 38,
    carbs: 12,
    fat: 28,
    ingredients: [
      { id: "1", name: "Chicken Breast", amount: 4, unit: "pieces" },
      { id: "2", name: "Heavy Cream", amount: 1, unit: "cup" },
      { id: "3", name: "Sun-dried Tomatoes", amount: 0.5, unit: "cup" },
      { id: "4", name: "Spinach", amount: 2, unit: "cups" },
      { id: "5", name: "Parmesan Cheese", amount: 0.5, unit: "cup" },
      { id: "6", name: "Garlic", amount: 3, unit: "cloves" },
    ],
    instructions: [
      "Season chicken breasts with salt and pepper.",
      "Heat oil in a large skillet over medium-high heat.",
      "Cook chicken for 6-7 minutes per side until golden and cooked through. Remove and set aside.",
      "In the same skillet, add garlic and cook for 30 seconds.",
      "Add heavy cream, sun-dried tomatoes, and parmesan. Simmer for 3 minutes.",
      "Add spinach and cook until wilted.",
      "Return chicken to the skillet and spoon sauce over it.",
      "Serve hot with your favorite side.",
    ],
    creatorId: "user1",
    creatorName: "Chef Maria",
    creatorAvatar: "/placeholder.svg?height=40&width=40",
    createdAt: "2024-01-15",
    likes: 234,
    isLiked: false,
    isSaved: false,
  },
  {
    id: "2",
    slug: "avocado-toast-supreme",
    title: "Avocado Toast Supreme",
    description: "Elevated avocado toast with poached eggs, cherry tomatoes, and microgreens.",
    image: "/placeholder.svg?height=400&width=600",
    categories: ["breakfast", "healthy", "vegetarian"],
    difficulty: "easy",
    time: 15,
    servings: 2,
    calories: 320,
    protein: 14,
    carbs: 28,
    fat: 18,
    ingredients: [
      { id: "1", name: "Sourdough Bread", amount: 2, unit: "slices" },
      { id: "2", name: "Avocado", amount: 1, unit: "whole" },
      { id: "3", name: "Eggs", amount: 2, unit: "pieces" },
      { id: "4", name: "Cherry Tomatoes", amount: 6, unit: "pieces" },
      { id: "5", name: "Microgreens", amount: 0.25, unit: "cup" },
    ],
    instructions: [
      "Toast the sourdough bread until golden brown.",
      "Mash avocado with salt, pepper, and a squeeze of lemon.",
      "Poach eggs in simmering water for 3-4 minutes.",
      "Spread mashed avocado on toast.",
      "Top with poached egg, halved cherry tomatoes, and microgreens.",
      "Season with salt, pepper, and red pepper flakes.",
    ],
    creatorId: "user2",
    creatorName: "Alex Kitchen",
    creatorAvatar: "/placeholder.svg?height=40&width=40",
    createdAt: "2024-01-20",
    likes: 189,
    isLiked: true,
    isSaved: true,
  },
  {
    id: "3",
    slug: "chocolate-lava-cake",
    title: "Chocolate Lava Cake",
    description: "Decadent individual chocolate cakes with a molten center.",
    image: "/placeholder.svg?height=400&width=600",
    categories: ["dessert", "chocolate", "baking"],
    difficulty: "hard",
    time: 25,
    servings: 4,
    calories: 380,
    protein: 6,
    carbs: 42,
    fat: 22,
    ingredients: [
      { id: "1", name: "Dark Chocolate", amount: 4, unit: "oz" },
      { id: "2", name: "Butter", amount: 0.5, unit: "cup" },
      { id: "3", name: "Eggs", amount: 2, unit: "pieces" },
      { id: "4", name: "Egg Yolks", amount: 2, unit: "pieces" },
      { id: "5", name: "Sugar", amount: 0.25, unit: "cup" },
      { id: "6", name: "Flour", amount: 2, unit: "tbsp" },
    ],
    instructions: [
      "Preheat oven to 425°F. Grease 4 ramekins.",
      "Melt chocolate and butter together in a double boiler.",
      "Whisk eggs, egg yolks, and sugar until thick and pale.",
      "Fold chocolate mixture into eggs, then fold in flour.",
      "Divide batter among ramekins.",
      "Bake for 12-14 minutes until edges are firm but center is soft.",
      "Let cool 1 minute, then invert onto plates.",
      "Serve immediately with ice cream or whipped cream.",
    ],
    creatorId: "user3",
    creatorName: "Pastry Pro",
    creatorAvatar: "/placeholder.svg?height=40&width=40",
    createdAt: "2024-01-22",
    likes: 412,
    isLiked: false,
    isSaved: true,
  },
  {
    id: "4",
    slug: "grilled-salmon-bowl",
    title: "Grilled Salmon Bowl",
    description: "Fresh and nutritious salmon bowl with quinoa and roasted vegetables.",
    image: "/placeholder.svg?height=400&width=600",
    categories: ["lunch", "healthy", "seafood"],
    difficulty: "medium",
    time: 30,
    servings: 2,
    calories: 520,
    protein: 42,
    carbs: 35,
    fat: 24,
    ingredients: [
      { id: "1", name: "Salmon Fillet", amount: 2, unit: "pieces" },
      { id: "2", name: "Quinoa", amount: 1, unit: "cup" },
      { id: "3", name: "Broccoli", amount: 2, unit: "cups" },
      { id: "4", name: "Sweet Potato", amount: 1, unit: "medium" },
      { id: "5", name: "Avocado", amount: 1, unit: "whole" },
    ],
    instructions: [
      "Cook quinoa according to package directions.",
      "Cube sweet potato and roast at 400°F for 20 minutes.",
      "Season salmon with salt, pepper, and olive oil.",
      "Grill salmon for 4-5 minutes per side.",
      "Steam broccoli until tender-crisp.",
      "Assemble bowls with quinoa, vegetables, and salmon.",
      "Top with sliced avocado and your favorite dressing.",
    ],
    creatorId: "user1",
    creatorName: "Chef Maria",
    creatorAvatar: "/placeholder.svg?height=40&width=40",
    createdAt: "2024-01-25",
    likes: 156,
    isLiked: false,
    isSaved: false,
  },
  {
    id: "5",
    slug: "classic-margherita-pizza",
    title: "Classic Margherita Pizza",
    description: "Traditional Italian pizza with fresh mozzarella, tomatoes, and basil.",
    image: "/placeholder.svg?height=400&width=600",
    categories: ["dinner", "italian", "vegetarian"],
    difficulty: "medium",
    time: 45,
    servings: 4,
    calories: 285,
    protein: 12,
    carbs: 36,
    fat: 10,
    ingredients: [
      { id: "1", name: "Pizza Dough", amount: 1, unit: "lb" },
      { id: "2", name: "San Marzano Tomatoes", amount: 1, unit: "can" },
      { id: "3", name: "Fresh Mozzarella", amount: 8, unit: "oz" },
      { id: "4", name: "Fresh Basil", amount: 10, unit: "leaves" },
      { id: "5", name: "Olive Oil", amount: 2, unit: "tbsp" },
    ],
    instructions: [
      "Preheat oven to 500°F with pizza stone inside.",
      "Stretch dough into a 12-inch circle.",
      "Crush tomatoes and spread over dough.",
      "Tear mozzarella and distribute evenly.",
      "Drizzle with olive oil.",
      "Bake for 10-12 minutes until crust is golden.",
      "Top with fresh basil leaves.",
      "Slice and serve immediately.",
    ],
    creatorId: "user4",
    creatorName: "Pizza Master",
    creatorAvatar: "/placeholder.svg?height=40&width=40",
    createdAt: "2024-01-28",
    likes: 298,
    isLiked: true,
    isSaved: false,
  },
  {
    id: "6",
    slug: "berry-smoothie-bowl",
    title: "Berry Smoothie Bowl",
    description: "Refreshing açaí smoothie bowl topped with fresh berries and granola.",
    image: "/placeholder.svg?height=400&width=600",
    categories: ["breakfast", "healthy", "vegan"],
    difficulty: "easy",
    time: 10,
    servings: 1,
    calories: 340,
    protein: 8,
    carbs: 62,
    fat: 8,
    ingredients: [
      { id: "1", name: "Açaí Packet", amount: 1, unit: "packet" },
      { id: "2", name: "Banana", amount: 1, unit: "whole" },
      { id: "3", name: "Mixed Berries", amount: 1, unit: "cup" },
      { id: "4", name: "Almond Milk", amount: 0.5, unit: "cup" },
      { id: "5", name: "Granola", amount: 0.25, unit: "cup" },
    ],
    instructions: [
      "Blend açaí packet, banana, half the berries, and almond milk until smooth.",
      "Pour into a bowl.",
      "Top with remaining berries, granola, and any other toppings.",
      "Serve immediately.",
    ],
    creatorId: "user2",
    creatorName: "Alex Kitchen",
    creatorAvatar: "/placeholder.svg?height=40&width=40",
    createdAt: "2024-02-01",
    likes: 167,
    isLiked: false,
    isSaved: true,
  },
]

export const categories = [
  "all",
  "breakfast",
  "lunch",
  "dinner",
  "dessert",
  "healthy",
  "vegetarian",
  "vegan",
  "italian",
  "seafood",
  "chicken",
  "baking",
]

export const difficulties = ["easy", "medium", "hard"]
